name: Ping Search API Route

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send a ping request
        run: curl -X GET https://mojime-api.vercel.app/api/searchV2
